#!/usr/bin/ruby

def get_open_windows
	windows = []

	`wmctrl -lp`.split("\n").each do |line|
		line_array = line.split(/\s+/)

		id    = line_array.shift      # 0
		line_array.shift              # 1 remove unkown element
		pid   = line_array.shift.to_i # 2
		line_array.shift              # 3 remove unkown element
		title = line_array.join(' ')  # 4 join the rest

		next if pid == 0

		process_name = ''
		app_name     = ''

		process_name = `ps -fwwp #{pid} | tail -n 1`.split(" ")[7] unless pid == 0

		if process_name != ''
			desktop_file = "/usr/share/applications/#{process_name}.desktop"
			app_name     = `cat #{desktop_file} | grep Name= | head -n 1 | cut -d= -f 2`.strip if File.exists?(desktop_file)
		end

		windows << {
			:id            => id,
			:process_name  => process_name,
			:app_name      => app_name,
			:pid           => pid,
			:title         => title
		}
	end

	return windows
end

windows = get_open_windows()

# don't show dialog
# if no windows open
exit(0) if windows.length == 0

TITLE   = 'Close applications'
TEXT    = 'Do you want to close these application windows?'
COLUMNS = ['', 'PID', 'Application', 'Title']
WIDTH   = 550
HEIGHT  = 400

table_head = COLUMNS.map{|c| "--column \"#{c}\""}.join(' ')
table_body = windows.map do |win|
	app_name = win[:app_name]
	app_name = win[:process_name] if app_name.empty?

	"TRUE #{win[:pid]} \"#{app_name}\" \"#{win[:title]}\""
end.join(' ')

command = "zenity --width #{WIDTH} --height #{HEIGHT} --list --title \"#{TITLE}\" --text \"#{TEXT}\" --checklist #{table_head} #{table_body}"

output = `#{command}`

puts "OUTPUT: #{output}"

`close-all-windows --only #{output.gsub('|', ',')}` unless output == ''
exit($?.exit_status)